services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pedidosapp-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin@2026"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - pedidosapp_network

  adminer:
    image: adminer:latest
    container_name: pedidosapp-adminer
    ports:
      - "8081:8080"
    depends_on:
      - sqlserver
      - mongodb
    networks:
      - pedidosapp_network

  mongodb:
    image: mongo:latest
    container_name: pedidosapp-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - pedidosapp_network

  mongo-express:
    image: mongo-express:latest
    container_name: pedidosapp-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8082:8081"
    depends_on:
      - mongodb
    networks:
      - pedidosapp_network

volumes:
  sqlserver_data:
  mongodb_data:

networks:
  pedidosapp_network:
    driver: bridge